apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook-deployment
  labels:
    app: notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notebook
  template:
    metadata:
      labels:
        app: notebook
    spec:
      containers:
      - name: notebook
        image: adguchiya/notebook:latest
        ports:
        - containerPort: 8002