apiVersion: apps/v1
kind: Deployment
metadata:
  name: noteapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: noteapp
  template:
    metadata:
      labels:
        app: noteapp
    spec:
      containers:
      - name: noteapp
        image: adguchiya/noteapp:latest
        ports:
        - containerPort: 9696
